language: php

sudo: false

php:
  - 5.5
  - 5.6

env:
  global:
    - SYMFONY_VERSION=3.4.*

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION=3.4.*
        - php: 7.0
          env: SYMFONY_VERSION=3.4.*
        - php: 7.1
          env: SYMFONY_VERSION=3.4.*
        - php: 5.6
          env: SYMFONY_VERSION=dev-master
        - php: hhvm-3.18
          sudo: required
          group: edge
          env: SYMFONY_VERSION=3.4.*
    fast_finish: true
    allow_failures:
        - env: SYMFONY_VERSION=dev-master

before_script:
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d && echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer update --dev

script: ./vendor/bin/phpunit --coverage-text

notifications:
  email:
    - open-source@theodo.fr
